services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 5s
      retries: 5
  
  app:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - APP_PORT=3000
    volumes:
      - .:/app/
    depends_on:
      db:
        condition: service_healthy